services:
  # app:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: ./
  #   environment:
  #     - APP__DB__URL=postgresql+asyncpg://user:password@pg:5432/db
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     pg:
  #       condition: service_healthy
  #   develop:
  #     watch:
  #       - action: sync+restart
  #         path: ./app
  #         target: /src

  pg:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      pg:
        condition: service_healthy

volumes:
  pgdata: {}
