"""create audio & playlist & playlist_audio_association tables

Revision ID: 4d4b1aff979a
Revises: 77905d3fd2b9
Create Date: 2025-06-06 17:13:49.344819

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d4b1aff979a"
down_revision: Union[str, None] = "77905d3fd2b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlists",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlists")),
    )
    op.create_table(
        "audios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=250), nullable=False),
        sa.Column("uploader_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploader_id"],
            ["users.id"],
            name=op.f("fk_audios_uploader_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audios")),
        sa.UniqueConstraint("title", name=op.f("uq_audios_title")),
    )
    op.create_table(
        "playlist_audio_association",
        sa.Column("playlist_id", sa.UUID(), nullable=False),
        sa.Column("audio_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_id"],
            ["audios.id"],
            name=op.f("fk_playlist_audio_association_audio_id_audios"),
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
            name=op.f("fk_playlist_audio_association_playlist_id_playlists"),
        ),
        sa.PrimaryKeyConstraint(
            "playlist_id",
            "audio_id",
            name=op.f("pk_playlist_audio_association"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_audio_association")
    op.drop_table("audios")
    op.drop_table("playlists")
    # ### end Alembic commands ###
